# Generated by Django 3.1 on 2020-08-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Determine date of term (in YYYY-MM-DD form):'),
        ),
    ]
