# Generated by Django 3.1 on 2020-08-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200821_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='date',
            field=models.DateField(verbose_name='Determine date of term (in YYYY-MM-DD form):'),
        ),
    ]
