# Generated by Django 3.1 on 2020-08-21 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200821_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='time_from',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Determine beginning time (in HH:MM form)'),
        ),
        migrations.AlterField(
            model_name='term',
            name='time_to',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Determine ending time (in HH:MM form)'),
        ),
    ]
