# Generated by Django 3.1 on 2020-08-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200821_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='time_from',
            field=models.TimeField(verbose_name='Determine beginning time (in HH:MM form)'),
        ),
        migrations.AlterField(
            model_name='term',
            name='time_to',
            field=models.TimeField(verbose_name='Determine ending time (in HH:MM form)'),
        ),
    ]
