# Generated by Django 3.1 on 2020-08-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200821_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='medical_title',
            field=models.CharField(default='medical', max_length=64, verbose_name='medical title'),
        ),
    ]
