# Generated by Django 3.1 on 2020-08-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20200822_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='medical_title',
            field=models.CharField(max_length=64, verbose_name='medical title'),
        ),
    ]
