# Generated by Django 3.1 on 2020-08-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20200822_1711'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='term',
            order_with_respect_to='date',
        ),
    ]
