# Generated by Django 3.1 on 2020-08-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20200822_2134'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='term',
            order_with_respect_to=None,
        ),
    ]
