# Generated by Django 3.1 on 2020-08-25 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0010_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='visit',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='appointment',
        ),
        migrations.AddField(
            model_name='complaint',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.term', verbose_name='related appointment'),
        ),
        migrations.AlterField(
            model_name='term',
            name='date',
            field=models.DateField(validators=[registration.models.check_correct_data], verbose_name='Determine date of term (in YYYY-MM-DD form):'),
        ),
        migrations.RemoveField(
            model_name='term',
            name='user',
        ),
        migrations.AddField(
            model_name='term',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
