# Generated by Django 3.1 on 2020-08-25 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0011_auto_20200825_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.term', verbose_name='related appointment'),
        ),
        migrations.AlterField(
            model_name='term',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
