# Generated by Django 3.1 on 2020-08-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
    ]
