# Generated by Django 3.1 on 2020-08-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default='img/doctors/doctors-1.jpg', null=True, upload_to='img/'),
        ),
    ]
