# Generated by Django 3.1 on 2020-08-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20200830_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default='img/doctors/doctors-4.jpg', null=True, upload_to='img4/'),
        ),
    ]
