# Generated by Django 3.1 on 2020-09-05 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_specialisation_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'Complaint', 'verbose_name_plural': 'Complaint'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctor'},
        ),
        migrations.AlterModelOptions(
            name='specialisation',
            options={'verbose_name': 'Specialisation', 'verbose_name_plural': 'Specialisation'},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'verbose_name': 'Term', 'verbose_name_plural': 'Term'},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='term',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='registration.term', verbose_name='related appointment'),
        ),
    ]
